---
- name: clone git repository to roles directory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: ensure roles directory exists
      file:
        path: "roles"
        state: directory

    - name: clone thre git repository into roles directory
      git:
        repo: "git@github.com:nikita-talalai/ansible-roles.git"
        dest: "roles"
        version: master
        force: yes
